apiVersion: v1
kind: Service
metadata:
  name: market-order-service
spec:
  selector:
    run: market-order-service
  type: NodePort
  ports:
    - port: 4003
      targetPort: 4003
      nodePort: 30107