apiVersion: v1
kind: Service
metadata:
  name: market-article-service
spec:
  selector:
    run: market-article-service
  type: NodePort
  ports:
    - port: 4001
      targetPort: 4001
      nodePort: 30105