apiVersion: v1
kind: Service
metadata:
  name: market-zuul-service
spec:
  selector:
    run: market-zuul-service
  type: NodePort
  ports:
    - port: 9004
      targetPort: 9004
      nodePort: 30101