pipeline {

    agent any
    
    stages {

        stage('Build data base') {
             when {
                
                expression { env.gitlabTargetBranch == 'B_messaging' }
                
            }
            steps { 
			   script {
			    docker.withServer('tcp://35.180.206.6:4243') {
                        sh 'docker run -d --restart=always -p 32504:27017 --network=mysubnet --network-alias=market-messagingdb --name=market-messagingdb mongo || true'
                    }
			 
               }
            
        }
}
        stage('Build image Ms User') {
             when {
                
                expression { env.gitlabTargetBranch == 'B_messaging' }
            }
            steps { 
            dir ('MS_messaging') {
			   script {
			    docker.withServer('tcp://35.180.206.6:4243') {
                        sh 'docker build --build-arg DOCKER_ENV=dev . -t anonyme5/mmsimage:latest'
                        sh 'docker login -u anonyme5 -p Five12345'
                        sh 'docker push anonyme5/mmsimage:latest'
                    }
			 
               }
            }
        }
}
    stage('run in dev') {
          when {
                
                expression { env.gitlabTargetBranch == 'B_messaging' }
            }
            steps {
				script {
				docker.withServer('tcp://35.180.206.6:4243') {
				        sh 'docker rm --force market-messaging-service || true'
                        sh 'docker run --restart=always -d -p 4004:4004 --network=mysubnet --network-alias=market-messaging-service --name=market-messaging-service   anonyme5/mmsimage:latest'
                    }
				}
			   
              
            }
        }
     stage('Run in PRE-PROD Env') {
        when {
                beforeAgent true
                expression { env.gitlabTargetBranch == 'develop' }
            }
            agent {
          kubernetes {
            cloud "kubernetes"
           label "kube"
          }
        }
            steps {
				script {
				 container('kubectl') {
                 sh 'kubectl delete deploy market-messaging-service -n jenkins  || true'
                 sh 'kubectl apply -f  MS_messaging/messagingDB-deployment.yaml ' 
                     sh 'kubectl apply -f  MS_messaging/messaging-deployment.yaml '
                     sh 'kubectl apply -f  MS_messaging/messaging-service.yaml ' 
                     }
		}
			   
              
            }
        }
 stage('Run in PROD Env') {
        when {
                beforeAgent true
                expression { env.gitlabTargetBranch == 'release' }
            }
            agent {
          kubernetes {
            cloud "kubernetesProd"
           label "kubeProd"
          }
        }
            steps {
				script {
				 container('kubectl') {
                 sh 'kubectl delete deploy market-messaging-service -n jenkins  || true'
                 sh 'kubectl apply -f  MS_messaging/messagingDB-deployment.yaml ' 
                     sh 'kubectl apply -f  MS_messaging/messaging-deployment.yaml '
                     sh 'kubectl apply -f  MS_messaging/messaging-service.yaml ' 
                     }
		}
			   
              
            }
        }

    }
   
}