apiVersion: v1
kind: Service
metadata:
  name: market-messaging-service
spec:
  selector:
    run: market-messaging-service
  type: NodePort
  ports:
    - port: 4004
      targetPort: 4004
      nodePort: 30108