apiVersion: v1
kind: Service
metadata:
  name: market-user-service
spec:
  selector:
    run: market-user-service
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30104