apiVersion: v1
kind: Service
metadata:
  name: market-gallery-service
spec:
  selector:
    run: market-gallery-service
  type: NodePort
  ports:
    - port: 4005
      targetPort: 4005
      nodePort: 30109