apiVersion: v1
kind: Service
metadata:
  name: market-banner-service
spec:
  selector:
    run: market-banner-service
  type: NodePort
  ports:
    - port: 4006
      targetPort: 4006
      nodePort: 30110