// Generated by https://quicktype.io

export class Invoice {
  id: string;
  status: string;
  issueDate: string;
  amount: number;
  paid: number;
  discount?: number;
  to: InvoiceTo;
  items: Item[];

  get statusBadge(): string {
    let css = 'primary';

    switch (this.status) {
      case 'sent':
        css = 'primary';
        break;
      case 'late':
        css = 'danger';
        break;
      case 'draft':
        css = 'gray-light';
        break;
      case 'paid':
        css = 'success';
        break;
    }

    return css;
  }
}

export interface Item {
  title: string;
  description: string;
  price: number;
  quantity: number;
}

export interface InvoiceTo {
  name: string;
  email: string;
  location: Location;
}

export interface Location {
  street: Street;
  city: string;
  state: string;
  country: string;
  postcode: string;
  coordinates: Coordinates;
  timezone: Timezone;
}

export interface Coordinates {
  latitude: string;
  longitude: string;
}

export interface Street {
  number: number;
  name: string;
}

export interface Timezone {
  offset: string;
  description: string;
}
